name: Create node-network using Pulumi

on:
  workflow_dispatch:
    # inputs:
    #   name:
    #     description: 'Release name (v9.3.0 - Antioch)'
    #     required: true
    #   tag:
    #     description: 'Tag (v9.3.0)'
    #     required: true

# env:
#   REPOSITORY: joystream/node

jobs:
  up:
    name: Create Pulumi stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Start minikube
        uses: medyagh/setup-minikube@master

      - name: Create local stack
        run: |
          npm install
          pulumi login --local
          pulumi stack init dev
          pulumi config set-all --plaintext aws:region=us-east-1 --plaintext aws:profile=joystream-user \
            --plaintext numberOfValidators=2 --plaintext isMinikube=true --plaintext networkSuffix=8122 \
            --plaintext nodeImage=joystream/node:latest --plaintext encryptionKey=password
          cat Pulumi.dev.yaml
          kubectl get pods
        working-directory: devops/infrastructure/node-network
        env:
          PULUMI_CONFIG_PASSPHRASE:

      - uses: pulumi/actions@v3
        id: pulumi
        with:
          work-dir: devops/infrastructure/node-network
          command: up
          stack-name: dev
          cloud-url: file://~
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          PULUMI_CONFIG_PASSPHRASE:

      - name: Run kubectl commands
        run: |
          kubectl config set-context --current --namespace=${{ steps.pulumi.outputs.namespaceName }}
          kubectl get pods
          kubectl cp $(kubectl get pods | grep rpc-node | awk '{print $1}'):/chain-data/chain-data.7z ./chain-data.7z

      - name: Temporarily save node binary
        uses: actions/upload-artifact@v2
        with:
          name: chain-data.7z
          path: chain-data.7z
          retention-days: 1
