name: Deploy node network

on:
  workflow_dispatch:
    inputs:
      gitRepo:
        description: 'Code repository'
        required: false
        default: 'https://github.com/Joystream/joystream.git'
      branchName:
        description: 'Branch to deploy'
        required: false
        default: 'master'
      keyName:
        description: 'SSH key pair on AWS'
        required: false
        default: 'anuj-key'
      numberOfValidators:
        description: 'Number of validators to deploy'
        required: false
        default: '2'
      validatorInstanceType:
        description: 'AWS EC2 instance type for Validators (t2.micro, t2.large)'
        required: false
        default: 't2.large'
      buildInstanceType:
        description: 'AWS EC2 instance type for Build Instance (t2.micro, t2.large)'
        required: false
        default: 't2.xlarge'
      rpcInstanceType:
        description: 'AWS EC2 instance type for Validators (t2.micro, t2.large)'
        required: false
        default: 't2.large'
      ec2AMI:
        description: 'Pre-built AMI ID'
        required: false
        default: 'ami-0090c9c49dc765fbb'
      networkSuffix:
        description: 'Network suffix that will be added to the network name'
        required: false
        default: '8129'

defaults:
  run:
    working-directory: devops/aws

jobs:
  deploy-node-network:
    name: Create CloudFormation stack and run Ansible playbook
    runs-on: ubuntu-latest
    env:
      STACK_NAME: ga-node-network-${{ github.event.inputs.branchName }}-${{ github.run_number }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible dependencies
        run: pipx inject ansible-core boto3 botocore

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        id: deploy_stack
        with:
          name: ${{ env.STACK_NAME }}
          template: devops/aws/cloudformation/infrastructure.yml
          no-fail-on-empty-changeset: '1'
          parameter-overrides: >-
            KeyName=${{ github.event.inputs.keyName }},
            ValidatorEC2InstanceType=${{ github.event.inputs.validatorInstanceType }},
            RPCEC2InstanceType=${{ github.event.inputs.rpcInstanceType }},
            BuildEC2InstanceType=${{ github.event.inputs.buildInstanceType }},
            EC2AMI=${{ github.event.inputs.ec2AMI }},
            NumberOfValidators=${{ github.event.inputs.numberOfValidators }}

      - name: Prepare inventory for Ansible
        run: |
          ASG=${{ steps.deploy_stack.outputs.AutoScalingId }}

          VALIDATORS=""

          INSTANCES=$(aws autoscaling describe-auto-scaling-instances \
            --query "AutoScalingInstances[?AutoScalingGroupName=='${ASG}'].InstanceId" --output text);

          for ID in $INSTANCES
          do
            IP=$(aws ec2 describe-instances --instance-ids $ID --query "Reservations[].Instances[].PublicIpAddress" --output text)
            VALIDATORS+="$IP\n"
          done

          echo -e "[build]\n${{ steps.deploy_stack.outputs.BuildPublicIp }}\n" >> inventory
          echo -e "[validators]\n$VALIDATORS" >> inventory
          echo -e "[rpc]\n${{ steps.deploy_stack.outputs.RPCPublicIp }}" >> inventory
          cat inventory

      - name: Run playbook to compile joystream-node on build server
        uses: dawidd6/action-ansible-playbook@v2
        if: github.event.inputs.ec2AMI == ''
        with:
          playbook: build-code.yml
          directory: devops/aws
          requirements: requirements.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory
            --extra-vars "branch_name=${{ github.event.inputs.networkSuffix }} \
                          git_repo=${{ github.event.inputs.gitRepo }} data_path=mydata"

      - name: Run playbook to install additional utils on build server
        uses: dawidd6/action-ansible-playbook@v2
        if: github.event.inputs.ec2AMI == ''
        with:
          playbook: setup-admin.yml
          directory: devops/aws
          requirements: requirements.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory

      - name: Run playbook to configure chain-spec and pioneer
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: chain-spec-pioneer.yml
          directory: devops/aws
          requirements: requirements.yml
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          options: |
            --inventory inventory
            --extra-vars "network_suffix=${{ github.event.inputs.networkSuffix }} data_path=mydata \
                          number_of_validators=${{ github.event.inputs.numberOfValidators }} \
                          git_repo=${{ github.event.inputs.gitRepo }} deployment_type=live \
                          bucket_name=${{ steps.deploy_stack.outputs.S3BucketName }} \
                          branch_name=${{ github.event.inputs.branchName }}"

      - name: Save the output as an artifact
        uses: actions/upload-artifact@v2
        with:
          name: data-chainspec-auth
          path: devops/aws/mydata

      - name: Print output URL's
        run: |
          echo -e "Pioneer URL: https://${{ steps.deploy_stack.outputs.DomainName }}"
          echo -e "RPC: https://${{ steps.deploy_stack.outputs.RPCPublicIp }}.nip.io/ws-rpc"

      - name: Delete CloudFormation Stack if any step failed
        if: failure()
        run: |
          echo "Empty the bucket"
          aws s3 rm s3://${{ steps.deploy_stack.outputs.S3BucketName }} --recursive || echo "No bucket"
          echo "Deleting ${{ env.STACK_NAME }} stack"
          aws cloudformation delete-stack --stack-name ${{ env.STACK_NAME }}
          echo "Waiting for ${{ env.STACK_NAME }} to be deleted..."
          aws cloudformation wait stack-delete-complete --stack-name ${{ env.STACK_NAME }}
