name: Deploy docker-compose stack on AWS EC2

on:
  workflow_dispatch:
    inputs:
      gitRepo:
        description: 'Code repository'
        required: false
        default: 'https://github.com/Joystream/joystream.git'
      branchName:
        description: 'Branch to deploy'
        required: false
        default: 'master'
      keyName:
        description: 'SSH key pair on AWS'
        required: false
        default: 'joystream-github-action-key'
      instanceType:
        description: 'AWS EC2 instance type (t2.micro, t2.large)'
        required: false
        default: 't2.micro'

defaults:
  run:
    working-directory: devops/aws

jobs:
  run-docker-compose:
    name: Create an EC2 instance and configure docker-compose stack
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible dependencies
        run: pipx inject ansible-core boto3 botocore

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Prepare CloudFormation config
        run: |
          cp deploy-single-node.sample.cfg docker-deploy-config.cfg
          echo GIT_REPO=${{ github.event.inputs.gitRepo }} >> docker-deploy-config.cfg
          echo BRANCH_NAME=${{ github.event.inputs.branchName }} >> docker-deploy-config.cfg
          echo AWS_KEY_PAIR_NAME=${{ github.event.inputs.keyName }} >> docker-deploy-config.cfg
          echo DEFAULT_EC2_INSTANCE_TYPE=t2.xlarge >> docker-deploy-config.cfg
          cat docker-deploy-config.cfg

      - name: Create stack and run playbook
        run: |
          ./deploy-stack-docker-compose.sh docker-deploy-config.cfg
