name: Test Docker Cross

on:
  workflow_dispatch:

env:
  REPOSITORY: joystream/node
  KEY_NAME: joystream-github-action-key

jobs:
  build:
    name: Build the code and run setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2021-02-20
          default: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: '10.0'

      - id: run_rustup_setup
        name: Rustup setup
        run: |
          rustup install nightly-2021-02-20 --force
          rustup default nightly-2021-02-20
          rustup target add wasm32-unknown-unknown --toolchain nightly-2021-02-20
          rustup component add --toolchain nightly-2021-02-20 clippy
          sudo apt-get update && sudo apt-get install -y curl git gcc xz-utils sudo pkg-config unzip clang llvm libc6-dev libclang-dev

      - uses: Swatinem/rust-cache@v1

      - id: compute_shasum
        name: Compute runtime code shasum
        run: |
          export WASM_BUILD_TOOLCHAIN=nightly-2021-02-20
          BUILD_DUMMY_WASM_BINARY=1 cargo build --release
