---
# Run setup and build code

- name: Creat bash profile file
  command: "touch /home/ubuntu/.bash_profile"

- name: Run setup script
  command: ./setup.sh
  args:
    chdir: "{{ remote_code_path }}"

- name: Copy bash_profile content
  shell: cat ~/.bash_profile
  register: bash_data

- name: Copy bash_profile content to bashrc for non-interactive sessions
  blockinfile:
    block: "{{ bash_data.stdout }}"
    path: ~/.bashrc
    insertbefore: BOF

- name: Build joystream node
  command: ./scripts/cargo-build.sh
  args:
    chdir: "{{ remote_code_path }}"
  async: 2400
  poll: 0
  register: build_result

- name: Debug
  debug:
    msg: "Build started in async way"

- name: Check on build async task
  async_status:
    jid: "{{ build_result.ansible_job_id }}"
  register: job_result
  until: job_result.finished
  retries: 25
  delay: 100
