---
# Run setup and build code

- name: Creat bash profile file
  command: "touch /home/ubuntu/.bash_profile"

- name: Run setup script
  command: ./setup.sh
  args:
    chdir: "{{ remote_code_path }}"

- name: Build joystream node
  command: ./scripts/cargo-build.sh
  args:
    chdir: "{{ remote_code_path }}"
